# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-20 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=models.CharField(blank=True, help_text='可以为空', max_length=1024, verbose_name='摘要'),
        ),
    ]
